# Criando role para instalar nomad (servidor / cliente) #1
mentoriaiac/iac_role_nomad pull request #2
Opened 2021-07-25 18:58 UTC by cflb

- [x ] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x ] Dê um titulo que expresse o objetivo do PR
- [ x] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [ x] Descreva o objetivo do PR
- [ x] Inclua links relevantes para a sua modificação/sugestão/correção
- [x ] Descreva um passo-a-passo para testar o seu PR

# Criando role para instalar nomad (servidor / cliente)
## Descrição do PR

Role criada com molecule para Instalar nomad em um ubuntu latest. Criando também os templates para as configurações do modo nomand servidor/cliente. 

Se propõe a resolver ou iniciar uma resposta para a issue #1 

## Para testar 
>> molecule create
>> molecule coverge

## Issue

Se propõe a resolver a issue #1 
https://github.com/mentoriaiac/iac-role-nomad/issues/1

## Objetivo

Criar um role para nomad

## Referências

Encontro de nomad nas sextas-feiras

## Como testar

2021-08-01 17:40 UTC, cflb commented
Vou corrigir os erros que o linter está apresentando.

2021-08-01 18:49 UTC, gomex requested changes
Ta muito bom e só faltam detalhes.

2021-08-01 18:49 UTC, gomex commented on defaults/main.yml
> +nomad_group: nomad
Adicionar linha em branco.

2021-08-01 18:49 UTC, gomex commented on README.md
> -# Template Role Ansible
Precisamos traduzir esse README ;)

2021-08-01 18:49 UTC, gomex commented on meta/main.yml
> +  company: your company (optional)
Precisamos preencher esse meta

2021-08-01 18:49 UTC, gomex commented on molecule/default/molecule.yml
> +    image: docker.io/pycontribs/ubuntu
Falta a versão do ubuntu.

2021-08-01 18:49 UTC, gomex commented on tasks/main.yml
> +    - server.hcl.j2
Falta linha em branco no fim do arquivo.

2021-08-01 18:49 UTC, gomex commented on templates/client.hcl.j2
> +}
Falta linha em branco no fim do arquivo.

2021-08-01 18:49 UTC, gomex commented on templates/server.hcl.j2
> +}
Falta linha em branco no fim do arquivo.

2021-08-01 18:49 UTC, gomex commented on .travis.yml
> +---
Remover esse arquivo.

2021-08-01 18:49 UTC, gomex commented on molecule/default/verify.yml
> +      that: true
Seria legal ter um teste.

2021-08-15 02:07 UTC, cflb reviewed
Mudanças concluídas, o lint apresenta uma warn sobre a expressão regular que define o nome da role, e ela não valida 'HIFEM'
ela valida 'UNDERSCORE'

2021-08-15 02:07 UTC, cflb commented on .travis.yml
> +---
feito

2021-08-15 02:07 UTC, cflb commented on README.md
> -# Template Role Ansible
feito

2021-08-15 02:07 UTC, cflb commented on README.md
> -# Template Role Ansible
Algumas pessoas questionaram que o README poderia ser um pouco mais didatico, fiz algumas modificações.

2021-08-15 02:08 UTC, cflb commented
Mudanças concluídas, espero que esteja tudo OK!

2021-08-15 02:18 UTC, cflb reviewed
Traduzindo o readme e tentando deixar o texto um pouco mais didatico, mas posso só ter deixado mais prolixo.

2021-08-15 02:19 UTC, cflb commented on defaults/main.yml
> +nomad_group: nomad
feito

2021-08-15 02:20 UTC, cflb commented on meta/main.yml
> +  company: your company (optional)
Preenchido, também foi declarada a Plataform - Ubuntu 20.04 deveriamos usar a 18.04?

2021-08-15 02:21 UTC, cflb commented on molecule/default/molecule.yml
> +    image: docker.io/pycontribs/ubuntu
foi adicionado, e tambem a imagem do geerlingguy e a versão, contudo colocamos a 20.04

2021-08-15 02:22 UTC, cflb commented on tasks/main.yml
> +    - server.hcl.j2
feito

2021-08-15 02:24 UTC, cflb commented on templates/client.hcl.j2
> +}
feito

2021-08-16 01:17 UTC, gomex requested changes
Apenas um leve detalhe

2021-08-16 01:17 UTC, gomex commented on README.md
> +![Pipeline Status](https://github.com/mentoriaiac/template-role-ansible/actions/workflows/ci.yml/badge.svg)
Trocar o nome do link para o badger desse repo aqui.

2021-08-16 01:19 UTC, gomex approved these changes

2021-08-16 01:25 UTC, merged