Atualizando versão do Nomad para 1.3.1
mentoriaiac/iac_role_nomad pull request #26
Opened 2022-05-29 03:06 UTC by stephan-lopes

# Atualização de Versão do Nomad para 1.3.1

Atualiza a versão do Nomad para ser usada a versão mais recente.

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [x] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [x] Inclua links relevantes para a sua modificação/sugestão/correção
- [x] Descreva um passo-a-passo para testar o seu PR

## Issue

#25 

## Objetivo

Atualizar a versão do Nomad, para obter novos recursos das versões mais recentes, e corrigir a [CVE-2022-30324](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-30324).

## Referências

https://github.com/hashicorp/nomad/releases/tag/v1.3.1
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-30324

## Como testar

Com o clone do repositório em seu computador, e com os requisitos já instalados (Python 3 + Docker + PIP + Venv), instale as ferramentas com o comando `pip install -r requeriments.txt` em sua virtualenv. Após instalar, execute o molecule com o comando `molecule test`.

2022-05-29 11:44 UTC, EzzioWMoreira approved these changes

2022-06-11 00:14 UTC, lgfa29 requested changes
Marquei uma mudança pequena mas importante. Também seria legal adicionar uma entrada no [`CHANGELOG`](https://github.com/mentoriaiac/iac_role_nomad/blob/main/CHANGELOG.md). A gente esquece às vezes mas é bom manter atualizado 😄

2022-06-11 00:14 UTC, lgfa29 commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Eu não lembro se eu comentei na reunião, mas seria melhor colocar esse sufixo `-1` na variável `nomad_version` já que as versões mais antigas (`< 1.3.0`) não possuem, e pode ser que versões futuras precisem de um valor diferente.

2022-06-11 01:32 UTC, stephan-lopes commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Sim, falou sim. Mas lembro que tive problemas, não lembro se com linters, ou com a execução do playbook, quando o `-1` ficava dentro do `nomad_version`. Vou tentar reproduzir aqui novamente, para demonstrar o que estou falando.

2022-06-11 02:30 UTC, stephan-lopes commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Fui reproduzir o erro, mas ele passou. Antes tava dando erro na hora de checar a versão do nomad que estava instalada. Vou aplicar a mudança, e adicionar a entrada no `CHANGELOG`.

2022-06-11 02:35 UTC, stephan-lopes commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Quando a versão do nomad está como `1.3.1-1`, na segunda execução do `molecule test` (a primeira vez ele passa), ele dá esse erro, na hora de checar a versão instalada do nomad.

Apliquei o `-1` no `apt` por conta deste problema.

![image](https://user-images.githubusercontent.com/40838038/173169318-dd9c455f-a65b-4103-9de6-04a5bbfbcb70.png)

2022-06-11 15:16 UTC, gomex commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Nesse caso precisamos corrigir o verify do molecule: https://github.com/mentoriaiac/iac_role_nomad/blob/d7e27ec0dd137f881517a4efacbb59f6c63c4c5e/molecule/default/verify.yml#L18

O ideal seria usar alguma função do ansible pra remover o -1 do final :D 

Poderia ser assim

```
"'{{nomad_version | regex_replace('-[0-9]$', '') }}' in nomad_version_output.stdout"
```

Obs: Eu não testei isso ok? apenas peguei na documentação mesmo. Esse regex_replace tiraria o final pra testar a versão, pois parece que o nomad não retorna esse valor.

2022-06-11 22:45 UTC, lgfa29 commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Ah verdade. Mas é, o problema é que nem sempre é `-1`. Esse valor é usado para versionar o pacote, então pode ser que seja outro valor ou, para versões antigas, nem tenha o sufixo.

A ideia do `regex_replace` é uma boa, acho que só seria bom colocar um `+` no final para pegar mais de um dígito:
```
"'{{nomad_version | regex_replace('-[0-9]+$', '') }}' in nomad_version_output.stdout"
```

Espero não errar um release 10 vezes, mas vai saber né? :sweat_smile: 

Uma outra opção é desacoplar os dois valores. Apesar de relacionadas, essas duas versões representam duas coisas diferentes. Ficaria assim:

```yaml
# defaults/main.yml
# ...
nomad_version: "1.3.1"
nomad_package_version: "1"
# ...
```

```yaml
# tasks/main.yml
# ...
- name: "Instalando Nomad"
  apt:
    name: "nomad={{ nomad_version }}-{{ nomad_package_version }}"
# ...
```

Aí eu acho que os testes vão passar sem modificação.

2022-06-12 15:26 UTC, gomex commented on tasks/main.yml
> +    name: "nomad={{ nomad_version }}-1"
Eu prefiro o uso da variável nomad_package_version.

2022-06-19 17:38 UTC, merged